-- MySQL Script generated by MySQL Workbench
-- Sun 01 May 2022 03:15:05 PM CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema web_forum
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema web_forum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `web_forum` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `web_forum` ;

-- -----------------------------------------------------
-- Table `web_forum`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_forum`.`categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `isPrivate` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `web_forum`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_forum`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8mb3' NOT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `googleId` VARCHAR(45) NULL DEFAULT NULL,
  `discordId` VARCHAR(45) NULL DEFAULT NULL,
  `banned` TINYINT(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `googleId_UNIQUE` (`googleId` ASC) VISIBLE,
  UNIQUE INDEX `discordId_UNIQUE` (`discordId` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 64
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `web_forum`.`threads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_forum`.`threads` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `categoryId` INT(11) NOT NULL,
  `creatorId` INT(11) NOT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `isLocked` TINYINT(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `threads_fk_category_id_idx` (`categoryId` ASC) VISIBLE,
  INDEX `threads_fk_creator_id_idx` (`creatorId` ASC) VISIBLE,
  CONSTRAINT `threads_fk_category_id`
    FOREIGN KEY (`categoryId`)
    REFERENCES `web_forum`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `threads_fk_creator_id`
    FOREIGN KEY (`creatorId`)
    REFERENCES `web_forum`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `web_forum`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_forum`.`comments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `text` TEXT NOT NULL,
  `threadId` INT(11) NOT NULL,
  `commenterId` INT(11) NOT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `comments_fk_thread_id_idx` (`threadId` ASC) VISIBLE,
  INDEX `comments_fk_commentor_id_idx` (`commenterId` ASC) VISIBLE,
  CONSTRAINT `comments_fk_commentor_id`
    FOREIGN KEY (`commenterId`)
    REFERENCES `web_forum`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `comments_fk_thread_id`
    FOREIGN KEY (`threadId`)
    REFERENCES `web_forum`.`threads` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `web_forum`.`discord_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_forum`.`discord_tokens` (
  `userId` INT(11) NOT NULL,
  `accessToken` VARCHAR(50) NOT NULL,
  `refreshToken` VARCHAR(50) NOT NULL,
  `expires` INT(11) NOT NULL,
  PRIMARY KEY (`userId`),
  CONSTRAINT `fk_discord_tokens_user_id`
    FOREIGN KEY (`userId`)
    REFERENCES `web_forum`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `web_forum`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_forum`.`permissions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `permission` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `permission_UNIQUE` (`permission` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 68
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `web_forum`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_forum`.`roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `role_UNIQUE` (`role` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `web_forum`.`role_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_forum`.`role_permissions` (
  `roleId` INT(11) NOT NULL,
  `permissionId` INT(11) NOT NULL,
  PRIMARY KEY (`roleId`, `permissionId`),
  INDEX `fkPermissionId_idx` (`permissionId` ASC) VISIBLE,
  CONSTRAINT `role_permissions_fk_permission_id`
    FOREIGN KEY (`permissionId`)
    REFERENCES `web_forum`.`permissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_permissions_fk_role_id`
    FOREIGN KEY (`roleId`)
    REFERENCES `web_forum`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `web_forum`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_forum`.`user_roles` (
  `userId` INT(11) NOT NULL,
  `roleId` INT(11) NOT NULL,
  `context` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`userId`, `roleId`, `context`),
  INDEX `fkRoleId_idx` (`roleId` ASC) VISIBLE,
  CONSTRAINT `user_roles_fk_role_id`
    FOREIGN KEY (`roleId`)
    REFERENCES `web_forum`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_roles_fk_user_id`
    FOREIGN KEY (`userId`)
    REFERENCES `web_forum`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
